dailyfresh/apps/carts/urls.py
from django.contrib import admin
from django.urls import path,include
from carts.views import CartAddView,CartInfoView,CartUpdateView,CartDeleteView
urlpatterns = [
    path("add/",CartAddView.as_view(),name='add'),# 购物车记录添加
    path("",CartInfoView.as_view(),name='cart'), # 购物车显示
    path("update/",CartUpdateView.as_view(),name='update'), #购物车更新
    path("delete/",CartDeleteView.as_view(),name='delete'), #购物车商品删除
]

dailyfresh/apps/goods/urls.py
from django.contrib import admin
from django.urls import path,include
from goods.views import IndexView,DetailView,ListView
urlpatterns = [
    # path("index/", IndexView.as_view(),name="index"),
    path("", IndexView.as_view(),name="index"), # 首页
    path("goods/<int:goods_id>/",DetailView.as_view(),name="detail"), #详情页
    path("list/<int:type_id>/<int:page>/",ListView.as_view(),name="list"), #列表页
]

dailyfresh/apps/user/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import RegisterView,ActiveView,LoginView,UserInfoView\
    ,UserOrderView,AddressView,LogoutView

urlpatterns = [
    # path("register/", views.register,name="register"),#注册
    # path("register_handle/", views.register_handle,name="register_handle"),#注册处理
    path("register/",RegisterView.as_view(),name="register"),# 用户注册界面
    path("active/<str:str>/",ActiveView.as_view(),name="active"),# 用户激活界面
    path("login/",LoginView.as_view(),name="login"),# 用户登录界面
    path("",UserInfoView.as_view(),name="user"),# 用户的信息页面
    path("order/<int:page>/", UserOrderView.as_view(), name="order"),  # 用户的订单页面
    path("address/", AddressView.as_view(), name="address"),  # 用户的地址页面
    path("logout/",LogoutView.as_view(),name="logout"), # 用户退出登录

]

dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path("tinymce/",include("tinymce.urls")),
    path("search/",include('haystack.urls')),# 全文解锁
    path("user/", include(("user.urls","user"),namespace="user")), #用户模块
    path("cart/",include(("carts.urls","carts"),namespace="cart")),#购物车模块
    path("order/", include(("order.urls","order"),namespace="order")),#订单模块
    path("", include(("goods.urls","goods"),namespace="goods")), #商品模块

]

dailyfresh/apps/carts/models.py
from django.db import models

# Create your models here.

dailyfresh/apps/carts/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.Mixin import LoginRequiredMinin
# Create your views here.

class CartAddView(View):
    """购物车记录添加"""
    def post(self,request):
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res':0,'errmsg':'请先登录'})

        # 接受数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except Exception:
            return JsonResponse({'res':3,'errmsg':'商品不存在'})

        # 业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # 尝试获取sku_id的值->hget cart_key属性
        # 如果sku_id在hash中存在，hget返回none
        cart_count = conn.hget(cart_key,sku_id)
        if cart_count:
            # 累加购物车中商品的数目
            count += int(cart_count)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res':4,'errmsg':'商品库存不足'})

        # 设置hash中的sku_id对应的值
        conn.hset(cart_key,sku_id,count)

        # 计算用户购物车商品的条目数
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res':5,'total_count':total_count,'errmsg':'添加成功'})


# /cart
class CartInfoView(LoginRequiredMinin,View):
    '''购物车页面显示'''
    def get(self,request):
        # 获取登录的用户
        user = request.user
        # 获取用户购物车中的商品信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # {'商品id':商品数量}
        cart_dict = conn.hgetall(cart_key)

        skus = []
        # 保存用户购物车中商品的总数目和总价格
        total_count = 0
        total_price = 0
        # 遍历获取商品的信息
        for sku_id, count in cart_dict.items():
            # 根据商品的id获取商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price*int(count)
            # 动态给sku对象增加一个属性amount，保存商品小计
            sku.amount = amount
            # 动态给sku对象增加一个属性count，保存购物车对应的商品
            sku.count = int(count)
            # 添加
            skus.append(sku)
            # 累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        # 组织模板上下文
        context = {'total_count':total_count,
                   'total_price':total_price,
                   'skus':skus}

        return render(request,'cart.html',context)



# 购物车更新
# /cart/update
class CartUpdateView(LoginRequiredMinin,View):
    '''购物车记录更新'''
    def post(self,request):
        '''记录更新'''
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接受数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except Exception:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 检验商品的库存
        if count > sku.stock:
            return JsonResponse({'res':4,'errmsg':'商品库存不足'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res':5,'total_count':total_count,'message':'更新成功'})


# 使用ajax post请求 获取商品的id
# /cart/delete
class CartDeleteView(LoginRequiredMinin,View):
    '''购物车记录的删除'''
    def post(self,request):
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res':0,'errmsg':'请先登录'})

        # 接受参数
        sku_id = request.POST.get('sku_id')

        # 数据的校验
        if not sku_id:
            return JsonResponse({'res':1,'errmsg':'无效的商品id'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except Exception:
            return JsonResponse({'res':2,'errmsg':'商品不存在'})

        # 业务处理 删除商品
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 删除 hdel
        conn.hdel(cart_key, sku_id)
        return JsonResponse({'res':3,'total_count':total_count,'message':'删除成功'})

dailyfresh/templates/detail.html
<!DOCTYPE html>
<html >
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{% load static %}
	<title>天天生鲜-商品详情</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static './css/main.css' %}">

</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<form method="get" action="/search">
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
				<input type="submit" class="input_btn fr" name="" value="搜索">
			</form>
		</div>
		<div class="guest_cart fr">
			<a href="/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					{% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' sku.type.id 1 %}">{{ sku.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div>
				<p>其他规格：</p>
				<ul>
					{% for sku in same_spu_skus %}
						<li><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></li>
					{% endfor %}
				</ul>
			</div>

			<div class="total">总价：<em>16.80元</em></div>
			<div class="operate_btn">
				{% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" sku_id="{{ sku.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }} </dd>
				</dl>
			</div>

			<div class="tab_content">
				<dl>
					{% for order in sku_orders %}
					<dt>评论时间：{{ order.update_time }}&nbsp;&nbsp;用户名：{{ order.order.user.username }}</dt>
					<dd>评论内容：{{ order.comment }} </dd>
					{% endfor %}
				</dl>
			</div>

		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<div class="add_jump"></div>

	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">

		update_goods_amount()
		// 计算商品的总价格
		function update_goods_amount(){
			// 获取商品的单机和数量

			price = $('.show_pirze').children('em').text()
			count = $('.num_show').val()
			// 计算商品的总价
			price = parseFloat(price)
			count = parseInt(count)
			amount = price*count
			// 设置商品的总价
			$('.total').children('em').text(amount.toFixed(2)+'元')
		}

		// 增加商品的数量
		$('.add').click(function(){
			// 获取商品原有数目
			count = $('.num_show').val()
			// 加1
			count = parseInt(count)+1
			// 重新设置商品的数目
			$('.num_show').val(count)
			// 更新商品的总价
			update_goods_amount()

		})

		// 减少商品的数量
		$('.minus').click(function(){
			// 获取商品原有数目
			count = $('.num_show').val()
			// 减1
			count = parseInt(count)-1
			if (count<=0){
				count = 1
			}

			// 重新设置商品的数目
			$('.num_show').val(count)
			// 更新商品的总价
			update_goods_amount()

		})

		// 手动输入商品的数目
		$('.num_show').blur(function(){
			// 获取count是否合法
			count = $(this).val()
			// 校验count是否合法
			if (isNaN(count) || count.trim().length==0 || parseInt(count) <=0){
				count = 1
			}
			// 重设商品的数目
			$(this).val(parseInt(count))
			// 更新商品的总价
			update_goods_amount()
		})


		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$('#add_cart').click(function(){
			// 获取商品id和商品数量
			sku_id = $(this).attr('sku_id')
			count = $('.num_show').val()
			//alert(sku_id+':'+count)
			csrf = $("[name='csrfmiddlewaretoken']").val()
			// 组织参数
			params = {'sku_id':sku_id,'count':count,'csrfmiddlewaretoken':csrf}
			// 发起ajax post请求，访问/cart/add，传递参数：sku_id count

			$.post('/cart/add/',params,function(data){

				if (data.res == 5){
					// 添加成功
					$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
					$(".add_jump").stop().animate({
						'left': $to_y+7,
						'top': $to_x+7},
						"fast", function() {
						$(".add_jump").fadeOut('fast',function(){
							// 重设购物车商品数目
							$('#show_count').html(data.total_count);
						});
					});
				}
				else{
					// 添加失败
					alert(data.errmsg)
				}
			})




		})

	</script>
	
</body>
</html>

dailyfresh/templates/user_center_info.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<form method="get" action="/search">
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
				<input type="submit" class="input_btn fr" name="" value="搜索">
			</form>
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active" {% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active" {% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active" {% endif %}>· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user.username}}</li>
							{% if address %}
								<li><span>联系方式：</span>{{address.phone}}</li>
								<li><span>联系地址：</span>{{address.addr}}</li>
							{% else %}
								<li><span>联系方式：</span>无默认</li>
								<li><span>联系地址：</span>无默认</li>
							{% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
						{% for goods in goods_li %}
						<li>
							<a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
							<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
							<div class="operate">
								<span class="prize">{{goods.price}}</span>
								<span class="unit">{{goods.price}}/{{goods.unite}}</span>
								<a href="#" class="add_goods" title="加入购物车"></a>
							</div>
						</li>
						{% empty %}
							无历史浏览记录
						{% endfor %}
<!--					<li>-->
<!--					<a href="detail.html"><img src="images/goods/goods003.jpg"></a>-->
<!--					<h4><a href="detail.html">大兴大棚草莓</a></h4>-->
<!--					<div class="operate">-->
<!--						<span class="prize">￥16.80</span>-->
<!--						<span class="unit">16.80/500g</span>-->
<!--						<a href="#" class="add_goods" title="加入购物车"></a>-->
<!--					</div>-->
<!--					</li>-->
<!--				<li>-->
<!--					<a href="#"><img src="{% static 'images/goods/goods004.jpg' %}"></a>-->
<!--					<h4><a href="#">吐鲁番梨光杏</a></h4>-->
<!--					<div class="operate">-->
<!--						<span class="prize">￥5.50</span>-->
<!--						<span class="unit">5.50/500g</span>-->
<!--						<a href="#" class="add_goods" title="加入购物车"></a>-->
<!--					</div>-->
<!--				</li>-->

<!--				<li>-->
<!--					<a href="#"><img src="{% static 'images/goods/goods005.jpg' %}"></a>-->
<!--					<h4><a href="#">黄肉桃</a></h4>-->
<!--					<div class="operate">-->
<!--						<span class="prize">￥10.00</span>-->
<!--						<span class="unit">10.00/500g</span>-->
<!--						<a href="#" class="add_goods" title="加入购物车"></a>-->
<!--					</div>-->
<!--				</li>-->

<!--				<li>-->
<!--					<a href="#"><img src="{% static 'images/goods/goods006.jpg' %}"></a>-->
<!--					<h4><a href="#">进口西梅</a></h4>-->
<!--					<div class="operate">-->
<!--						<span class="prize">￥28.80</span>-->
<!--						<span class="unit">28.8/500g</span>-->
<!--						<a href="#" class="add_goods" title="加入购物车"></a>-->
<!--					</div>-->
<!--				</li>-->

<!--				<li>-->
<!--					<a href="#"><img src="{% static 'images/goods/goods007.jpg' %}"></a>-->
<!--					<h4><a href="#">香梨</a></h4>-->
<!--					<div class="operate">-->
<!--						<span class="prize">￥6.45</span>-->
<!--						<span class="unit">6.45/500g</span>-->
<!--						<a href="#" class="add_goods" title="加入购物车"></a>-->
<!--					</div>-->
<!--				</li>-->
			</ul>
		</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

dailyfresh/templates/user_center_site.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<form method="get" action="/search">
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
				<input type="submit" class="input_btn fr" name="" value="搜索">
			</form>
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active" {% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active" {% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active" {% endif %}>· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						{% if address %}
							<dd>{{address.addr}} （{{address.receiver}} 收） {{address.phone}}</dd>
						{% else %}
							<dd>无默认地址</dd>
						{% endif %}

					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post">
						{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receiver">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit"  value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>